FROM python:3.7-slim-buster

RUN mkdir /api

# Copy code
COPY api/. /api

COPY requirements.txt /requirements.txt
RUN pip install -r requirements.txt

# Copy model
WORKDIR /api
RUN mkdir models
COPY models/. models

# Copy metadatabase
WORKDIR /api
RUN mkdir -p ArtRecognition/data
COPY ArtRecognition/data/database.csv ArtRecognition/data

EXPOSE $PORT

CMD uvicorn fast:app --host "0.0.0.0" --port $PORT
